[package]
name = "jv"
version = "0.1.0"
authors = ["Dominic Bou-Samra <dominic.bou.samra@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
serde_json = "1.0.107"
tui = { package = "ratatui", version = "0.23.0" }
